language: php
php:
- 7.0
install:
- composer install
script:
- ./vendor/bin/phing test
before_install:
- phpenv config-add php7-config.ini
after_success:
- ./vendor/bin/coveralls -vvv;
notifications:
  email:
    recipients:
    - nils.destoop@wunderkraut.com
    - wouter.vanelslander@wunderkraut.com